version: "2"
services:
  # OpenOCD server
  redox-fw-openocd:
    image: redox-fw-openocd:latest
    network_mode: bridge
    ports:
      - "4444:4444"
    devices:
      - "/dev/bus"
  # Nordic SDK toolchain
  redox-fw-toolchain:
    image: redox-fw-toolchain:latest
    network_mode: bridge
    depends_on:
        - redox-fw-openocd
    links:
        - redox-fw-openocd
    command: tail -f /dev/null
