version: "2.4"
services:
  # OpenOCD server
  redox-fw-openocd:
    build:
        context: .
        dockerfile: Dockerfile_openocd
    image: redox-fw-openocd:latest
    network_mode: host
    devices:
      - "/dev/bus"
  # Nordic SDK toolchain
  redox-fw-toolchain:
    build:
        context: .
        dockerfile: Dockerfile_toolchain
    image: redox-fw-toolchain:latest
    network_mode: host
    depends_on:
        - redox-fw-openocd
    command: tail -f /dev/null
